import { Province, TourismCategory, TourismOperator, RegistrationApplication, MembershipRecord, LicenseRecord, OperatorCompliance, AuditLog, NotificationItem, DemoUser } from '../types';

export const DEMO_USERS: DemoUser[] = [
 {id:'user-admin-1',name:'Markus Kaumu',role:'admin',title:'Director of Policy & Licensing',department:'PNG Tourism Promotion Authority (PNG TPA)',avatar:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'},
 {id:'user-staff-1',name:'Grace Pakur',role:'staff',title:'Senior Registry & Compliance Officer',department:'PNG TPA Operations Division',avatar:'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80'},
 {id:'user-op-1',name:'John Wari',role:'operator',title:'Managing Director',department:'PNG Paradise Tours Ltd',avatar:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',operatorId:'op-png-paradise'},
 {id:'user-public-1',name:'Elena Rostova',role:'public',title:'International Traveler & Adventurer',department:'Public Tourism Directory',avatar:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80'}
];

const province=(id:string,name:string,region:Province['region'],capital:string,description:string,lat:number,lng:number,heroImage:string):Province=>({id,name,region,capital,description,heroImage,coordinates:{lat,lng}});
export const PROVINCES: Province[] = [
 province('ncd','National Capital District','Southern','Port Moresby','National capital and principal gateway for international and domestic tourism.',-9.4438,147.1803,'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&auto=format&fit=crop&q=80'),
 province('central','Central','Southern','Port Moresby','Kokoda access, coastal communities, mountain landscapes and cultural experiences.',-9.8000,147.6000,'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'),
 province('gulf','Gulf','Southern','Kerema','Wetlands, rivers, coastal communities and distinctive Gulf cultural landscapes.',-7.9636,145.7785,'https://images.unsplash.com/photo-1500534623283-312aade485b7?w=800&auto=format&fit=crop&q=80'),
 province('western','Western','Southern','Daru','Fly River landscapes, Lake Murray and remote wilderness tourism.',-9.0778,143.2092,'https://images.unsplash.com/photo-1511497584788-876760111969?w=800&auto=format&fit=crop&q=80'),
 province('milne-bay','Milne Bay','Southern','Alotau','Island cultures, marine adventures, reefs and community-based tourism.',-10.3167,150.4500,'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80'),
 province('oro','Oro (Northern)','Southern','Popondetta','Tufi fjords, coastal reefs, rainforest and World War II heritage.',-9.0833,149.3167,'https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=800&auto=format&fit=crop&q=80'),
 province('morobe','Morobe','Momase','Lae','Lae gateway, Huon Peninsula, rainforest and historical sites.',-6.7281,146.9944,'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80'),
 province('madang','Madang','Momase','Madang','Coastal, marine, island and village experiences around Madang.',-5.2167,145.8000,'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&auto=format&fit=crop&q=80'),
 province('east-sepik','East Sepik','Momase','Wewak','Sepik River cultural heritage, river journeys and traditional arts.',-3.5833,143.7000,'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800&auto=format&fit=crop&q=80'),
 province('sandaun','Sandaun (West Sepik)','Momase','Vanimo','Vanimo coast, surf, forests and frontier tourism experiences.',-2.6989,141.3028,'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&auto=format&fit=crop&q=80'),
 province('eastern-highlands','Eastern Highlands','Highlands','Goroka','Highland culture, coffee, birdlife and major cultural events.',-6.0833,145.3833,'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop&q=80'),
 province('western-highlands','Western Highlands','Highlands','Mount Hagen','Highland cultural tourism, gardens, landscapes and mountain experiences.',-5.8575,144.2267,'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80'),
 province('southern-highlands','Southern Highlands','Highlands','Mendi','Mountain landscapes, cultural traditions and community tourism.',-6.1471,143.6572,'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80'),
 province('hela','Hela','Highlands','Tari','Tari Valley, Huli cultural heritage and highland wildlife.',-5.8450,142.9460,'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80'),
 province('enga','Enga','Highlands','Wabag','Mountain valleys, cultural traditions and highland community experiences.',-5.4667,143.4333,'https://images.unsplash.com/photo-1464278533981-50106e6176b1?w=800&auto=format&fit=crop&q=80'),
 province('simp','Simbu (Chimbu)','Highlands','Kundiawa','Mountain scenery, coffee and distinctive highland cultural experiences.',-6.0167,144.9667,'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&auto=format&fit=crop&q=80'),
 province('east-new-britain','East New Britain','Islands','Kokopo','Volcanic landscapes, marine tourism and cultural traditions.',-4.3421,152.2683,'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'),
 province('west-new-britain','West New Britain','Islands','Kimbe','Kimbe Bay marine biodiversity, diving and island tourism.',-5.5500,150.1500,'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80'),
 province('new-ireland','New Ireland','Islands','Kavieng','Surf, reefs, island culture and historic sites.',-2.5744,150.7967,'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&auto=format&fit=crop&q=80'),
 province('manus','Manus','Islands','Lorengau','Remote island and marine tourism in the Admiralty Islands.',-2.0333,147.0000,'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80'),
 province('autonomous-bougainville','Autonomous Region of Bougainville','Islands','Buka','Island landscapes, marine tourism and cultural heritage.',-5.4300,154.6700,'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80'),
 province('national-highlands','National Highlands','Highlands','—','National highlands coverage placeholder for platform demonstration.',-5.9000,144.3000,'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&auto=format&fit=crop&q=80')
];

export const TOURISM_CATEGORIES: TourismCategory[] = [
 {id:'cat-trekking',name:'Trekking & Adventure',iconName:'Footprints',description:'Wilderness trails, mountain journeys and guided adventure.',badgeColor:'bg-emerald-100 text-emerald-800 border-emerald-300'},
 {id:'cat-diving',name:'Scuba Diving & Liveaboards',iconName:'Waves',description:'Reefs, wrecks and marine expeditions.',badgeColor:'bg-cyan-100 text-cyan-800 border-cyan-300'},
 {id:'cat-culture',name:'Cultural Festivals & Singsings',iconName:'Sparkles',description:'Cultural events, traditions, arts and community experiences.',badgeColor:'bg-amber-100 text-amber-800 border-amber-300'},
 {id:'cat-eco-lodge',name:'Eco-Lodges & Rainforest Retreats',iconName:'Trees',description:'Nature-based accommodation and rainforest experiences.',badgeColor:'bg-green-100 text-green-800 border-green-300'},
 {id:'cat-surfing',name:'Surfing & Coastal Expeditions',iconName:'Wind',description:'Surf, beaches, islands and coastal journeys.',badgeColor:'bg-blue-100 text-blue-800 border-blue-300'},
 {id:'cat-birdwatching',name:'Birdwatching & Wildlife Safaris',iconName:'Feather',description:'Wildlife, birds and specialist nature journeys.',badgeColor:'bg-purple-100 text-purple-800 border-purple-300'},
 {id:'cat-hospitality',name:'Hotels, Resorts & Lodging',iconName:'Hotel',description:'Hotels, resorts and accommodation.',badgeColor:'bg-rose-100 text-rose-800 border-rose-300'},
 {id:'cat-homestay',name:'Village Homestays & Community',iconName:'Home',description:'Community-based and village tourism.',badgeColor:'bg-orange-100 text-orange-800 border-orange-300'},
 {id:'cat-wwii-heritage',name:'WWII & Historical Heritage',iconName:'Landmark',description:'Historical places, memorials and heritage journeys.',badgeColor:'bg-stone-100 text-stone-800 border-stone-300'},
 {id:'cat-transport',name:'Tour Charters & Transport',iconName:'Compass',description:'Tour transport and charter services.',badgeColor:'bg-indigo-100 text-indigo-800 border-indigo-300'}
];

const op=(id:string,businessName:string,tradingName:string,operatorType:string,categoryId:string,province:string,district:string,lat:number,lng:number,description:string,heroImage:string):TourismOperator=>({id,businessName,tradingName,operatorType,categoryId,categoryName:TOURISM_CATEGORIES.find(c=>c.id===categoryId)?.name,province,district,address:`${district}, ${province}, Papua New Guinea`,contactPerson:'Demonstration Contact',email:'demo@pngtourism.example',phone:'+675 000 0000',website:'',description,latitude:lat,longitude:lng,registrationStatus:'Registered',membershipStatus:'Active',licenseStatus:'Active',complianceStatus:'Compliant',heroImage,galleryImages:[heroImage],features:['Demonstration listing','Tourism information','Contact operator'],priceRange:'Contact operator',createdDate:'2026-01-01T00:00:00Z',lastUpdatedDate:'2026-08-20T00:00:00Z'});
export const INITIAL_OPERATORS: TourismOperator[] = [
 op('op-png-paradise','PNG Paradise Tours Ltd','PNG Paradise Adventures','Tour Operator & Expeditions','cat-trekking','National Capital District','Moresby South',-9.479,147.1494,'Demonstration adventure operator profile for the prototype.','https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'),
 op('op-walindi-plantation','Walindi Plantation Resort Ltd','Walindi Dive Resort','Dive Resort & Liveaboard','cat-diving','West New Britain','Talasea',-5.4333,150.1,'Demonstration marine tourism listing for Kimbe Bay.','https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80'),
 op('op-tufi-dive-resort','Tufi Resort Operations Ltd','Tufi Dive & Cultural Resort','Resort & Adventure Specialist','cat-diving','Oro (Northern)','Ijivitari',-9.0833,149.3167,'Demonstration destination operator profile for Tufi.','https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80'),
 op('op-rabaul-tours','Volcano Sightseeing & Historical Tours Ltd','Rabaul Volcano & WWII Expeditions','Historical & Cultural Specialist','cat-wwii-heritage','East New Britain','Kokopo',-4.3421,152.2683,'Demonstration historical and volcanic tourism listing.','https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80'),
 op('op-tari-birding-lodge','Ambua Highlands Eco-Lodge Ltd','Ambua Lodge & Birding Sanctuary','Highland Eco-Lodge','cat-birdwatching','Hela','Tari-Pori',-5.845,142.946,'Demonstration highland nature tourism listing.','https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&auto=format&fit=crop&q=80'),
 op('op-goroka-cultural','Asaro Cultural Village Experience Ltd','Goroka Mudmen Cultural Homestays','Cultural & Community Tourism','cat-culture','Eastern Highlands','Daulo',-6.0833,145.3833,'Demonstration cultural and community tourism listing.','https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop&q=80'),
 op('op-alotau-canoe','Milne Bay Island Charters & Canoes','Milne Bay Coral Sea Expeditions','Marine & Cultural Outfitter','cat-culture','Milne Bay','Alotau',-10.3167,150.45,'Demonstration island and community tourism listing.','https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&auto=format&fit=crop&q=80'),
 op('op-kavieng-surf','Nusa Island Retreat Ltd','Nusa Island Surf & Eco Resort','Surf & Marine Retreat','cat-surfing','New Ireland','Kavieng',-2.5744,150.7967,'Demonstration surf and island tourism listing.','https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&auto=format&fit=crop&q=80'),
 op('op-madang-resort','Madang Resort & Kalibobo Cruises Ltd','Madang Resort Hotel & Marina','Luxury Hotel & Cruise Operator','cat-hospitality','Madang','Madang',-5.2167,145.8,'Demonstration hospitality listing.','https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&auto=format&fit=crop&q=80'),
 op('op-kokoda-track-expeditions','Fuzzy Wuzzy Kokoda Treks Ltd','Kokoda Trail Heritage Guides','Adventure & Trekking','cat-trekking','Central','Kairuku-Hiri',-9.4167,147.4167,'Demonstration Kokoda trekking listing.','https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80'),
 op('op-hagen-cultural-tours','Rondon Ridge Highlands Tours Ltd','Rondon Ridge Mountain Lodge','Eco-Lodge & Cultural Safaris','cat-eco-lodge','Western Highlands','Mount Hagen',-5.8575,144.2267,'Demonstration highland eco-tourism listing.','https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80'),
 op('op-lae-international','Lae City Hotel & Conference Ltd','Lae International Hotel','Business & Transit Hotel','cat-hospitality','Morobe','Lae Urban',-6.7281,146.9944,'Demonstration city hospitality listing.','https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80'),
 {...op('op-sepik-river-expeditions','Sepik River Canoe Safaris Ltd','Middle Sepik Cultural Tours','River & Cultural Expedition','cat-culture','East Sepik','Wewak',-3.5833,143.7,'Demonstration Sepik cultural tourism listing.','https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop&q=80'),registrationStatus:'Under Review',membershipStatus:'Pending',licenseStatus:'Pending',complianceStatus:'Conditional'},
 op('op-loloata-island','Loloata Island Resort Operations','Loloata Island Resort','Island Resort','cat-hospitality','National Capital District','Bootless Bay',-9.53,147.28,'Demonstration island resort listing.','https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80'),
 {...op('op-baining-wild','Baining Highlands Eco-Trek Ltd','Baining Wilderness Treks','Wilderness Hiking','cat-trekking','East New Britain','Gazelle',-4.45,152.05,'Demonstration wilderness trekking listing.','https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80'),registrationStatus:'Submitted',membershipStatus:'None',licenseStatus:'Pending',complianceStatus:'Conditional'}
];

export const INITIAL_REGISTRATIONS: RegistrationApplication[] = INITIAL_OPERATORS.filter(o=>o.registrationStatus!=='Registered').map((o,i)=>({id:`reg-${o.id}`,applicationNumber:`TPA-REG-2026-${String(44+i).padStart(4,'0')}`,operatorId:o.id,operatorName:o.businessName,status:o.registrationStatus,submittedDate:o.createdDate,history:[]}));
export const INITIAL_MEMBERSHIPS: MembershipRecord[] = INITIAL_OPERATORS.filter(o=>o.membershipStatus!=='None').map((o,i)=>({id:`mem-${o.id}`,membershipNumber:`TPA-MEM-2026-${String(i+1).padStart(4,'0')}`,operatorId:o.id,operatorName:o.businessName,membershipType:'Tour Operator Member',startDate:'2026-01-01',expiryDate:'2026-12-31',status:o.membershipStatus,feePaid:2500,notes:'Demonstration membership record — not an official certificate.'}));
export const INITIAL_LICENSES: LicenseRecord[] = INITIAL_OPERATORS.filter(o=>o.licenseStatus!=='None').map((o,i)=>({id:`lic-${o.id}`,licenseNumber:`TPA-LIC-2026-${String(i+1).padStart(4,'0')}`,operatorId:o.id,operatorName:o.businessName,licenseType:'Standard Tourism Commercial Licence',issueDate:'2026-01-01',expiryDate:'2026-12-31',status:o.licenseStatus,conditions:['Demonstration condition — replace with approved regulatory template'],notes:'Demonstration licence record — not an official licence.'}));
export const INITIAL_COMPLIANCE: Record<string,OperatorCompliance> = Object.fromEntries(INITIAL_OPERATORS.map(o=>[o.id,{operatorId:o.id,overallStatus:o.complianceStatus,lastAssessedDate:'2026-08-01T00:00:00Z',assessorNotes:'Demonstration compliance record.',requirements:[{id:`${o.id}-r1`,name:'Business registration evidence',category:'Legal',status:o.complianceStatus==='Compliant'?'Compliant':'Pending',documentRef:'DEMO-DOCUMENT.pdf'},{id:`${o.id}-r2`,name:'Operating licence evidence',category:'Legal',status:o.licenseStatus==='Active'?'Compliant':'Pending',documentRef:'DEMO-LICENCE.pdf'},{id:`${o.id}-r3`,name:'Insurance evidence',category:'Insurance',status:o.complianceStatus==='Compliant'?'Compliant':'Pending',documentRef:'DEMO-INSURANCE.pdf'},{id:`${o.id}-r4`,name:'Safety plan',category:'Safety',status:o.complianceStatus==='Compliant'?'Compliant':'Pending',documentRef:'DEMO-SAFETY.pdf'}]}]));
export const INITIAL_AUDIT_LOGS: AuditLog[]=[{id:'aud-demo-1',timestamp:'2026-08-20T08:30:00Z',user:'TPA Demo System',role:'System',action:'Demo dataset initialized',entity:'System',entityId:'DEMO',notes:'Illustrative prototype dataset.'}];
export const INITIAL_NOTIFICATIONS: NotificationItem[]=[];
