import express,{Request,Response,NextFunction}from'express';
import path from'path';
import{createServer as createViteServer}from'vite';
import{dbStore}from'./src/server/store';
const PORT=3000;

async function startServer(){const app=express();app.use(express.json());
 app.use((req,_res,next)=>{if(req.path.startsWith('/api'))console.log(`[API] ${req.method} ${req.path}`);next()});
 const getActor=(req:Request)=>({name:(req.headers['x-user-name']as string)||'Demo User',role:(req.headers['x-user-role']as string)||'staff'});
 const requireDemoWrite=(req:Request,res:Response,next:NextFunction)=>{if(!req.path.startsWith('/api')||req.method==='GET'){next();return}const actor=getActor(req);if(!['admin','staff','operator'].includes(actor.role)){res.status(403).json({error:'This demonstration action requires an authenticated platform role.'});return}next()};
 app.use('/api',requireDemoWrite);
 app.get('/api/health',(_req,res)=>res.json({status:'ok',service:'PNG Tourism Digital Platform - Prototype API',timestamp:new Date().toISOString(),version:'1.1-demo'}));
 app.post('/api/seed/reset',(req,res)=>{const actor=getActor(req);dbStore.resetToDefaults();dbStore.logAudit(actor.name,actor.role,'Database Reset','System','SEED-RESET',undefined,undefined,'Prototype dataset reset.');res.json({success:true})});
 app.get('/api/dashboard',(_req,res)=>res.json(dbStore.getDashboardAnalytics()));
 app.get('/api/audit-logs',(_req,res)=>res.json(dbStore.getAuditLogs()));
 app.get('/api/notifications',(req,res)=>res.json(dbStore.getNotifications(req.query.role as string,req.query.operatorId as string)));
 app.post('/api/notifications/:id/read',(req,res)=>{const item=dbStore.markNotificationRead(req.params.id);res.json({success:!!item,item})});
 app.get('/api/provinces',(_req,res)=>res.json(dbStore.getProvinces()));app.get('/api/categories',(_req,res)=>res.json(dbStore.getCategories()));
 app.get('/api/operators',(req,res)=>res.json(dbStore.getOperators({search:req.query.search as string,province:req.query.province as string,category:req.query.category as string,status:req.query.status as string,compliance:req.query.compliance as string})));
 app.post('/api/operators',(req,res)=>{try{res.status(201).json(dbStore.createOperator(req.body,getActor(req)))}catch(e:any){res.status(400).json({error:e.message})}});
 app.get('/api/operators/:id',(req,res)=>{const op=dbStore.getOperatorById(req.params.id);if(!op)return res.status(404).json({error:'Operator not found'});res.json(op)});
 app.put('/api/operators/:id',(req,res)=>{const op=dbStore.updateOperator(req.params.id,req.body,getActor(req));if(!op)return res.status(404).json({error:'Operator not found'});res.json(op)});
 app.get('/api/public/operators',(req,res)=>{const ops=dbStore.getOperators({search:req.query.search as string,province:req.query.province as string,category:req.query.category as string,publicOnly:true});res.json(ops.map(op=>({id:op.id,businessName:op.businessName,tradingName:op.tradingName,operatorType:op.operatorType,categoryId:op.categoryId,categoryName:op.categoryName,province:op.province,district:op.district,address:op.address,contactPerson:op.contactPerson,email:op.email,phone:op.phone,website:op.website,description:op.description,latitude:op.latitude,longitude:op.longitude,heroImage:op.heroImage,galleryImages:op.galleryImages,features:op.features,priceRange:op.priceRange,rating:op.rating,reviewCount:op.reviewCount,isVerified:false,hasActiveLicence:op.licenseStatus==='Active',demoData:true})))});
 app.get('/api/public/operators/:id',(req,res)=>{const op=dbStore.getOperatorById(req.params.id);if(!op||op.registrationStatus!=='Registered')return res.status(404).json({error:'Public listing not found'});res.json({id:op.id,businessName:op.businessName,tradingName:op.tradingName,operatorType:op.operatorType,categoryId:op.categoryId,categoryName:op.categoryName,province:op.province,district:op.district,address:op.address,contactPerson:op.contactPerson,email:op.email,phone:op.phone,website:op.website,description:op.description,latitude:op.latitude,longitude:op.longitude,heroImage:op.heroImage,galleryImages:op.galleryImages,features:op.features,priceRange:op.priceRange,rating:op.rating,reviewCount:op.reviewCount,isVerified:false,hasActiveLicence:op.licenseStatus==='Active',demoData:true})});
 app.get('/api/registrations',(_req,res)=>res.json(dbStore.getRegistrations()));app.post('/api/registrations',(req,res)=>{try{res.status(201).json(dbStore.createRegistration(req.body.operatorId,getActor(req),req.body.notes))}catch(e:any){res.status(400).json({error:e.message})}});app.get('/api/registrations/:id',(req,res)=>{const r=dbStore.getRegistrationById(req.params.id);if(!r)return res.status(404).json({error:'Registration not found'});res.json(r)});app.put('/api/registrations/:id/status',(req,res)=>{const r=dbStore.updateRegistrationStatus(req.params.id,req.body.status,getActor(req),req.body.notes);if(!r)return res.status(404).json({error:'Registration not found'});res.json(r)});
 app.get('/api/memberships',(_req,res)=>res.json(dbStore.getMemberships()));app.post('/api/memberships',(req,res)=>{try{res.status(201).json(dbStore.createMembership(req.body,getActor(req)))}catch(e:any){res.status(400).json({error:e.message})}});app.put('/api/memberships/:id/status',(req,res)=>{const m=dbStore.updateMembershipStatus(req.params.id,req.body.status,getActor(req),req.body.notes);if(!m)return res.status(404).json({error:'Membership not found'});res.json(m)});
 app.get('/api/licenses',(_req,res)=>res.json(dbStore.getLicenses()));app.post('/api/licenses',(req,res)=>{try{res.status(201).json(dbStore.createLicense(req.body,getActor(req)))}catch(e:any){res.status(400).json({error:e.message})}});app.put('/api/licenses/:id/status',(req,res)=>{const l=dbStore.updateLicenseStatus(req.params.id,req.body.status,getActor(req),req.body.notes);if(!l)return res.status(404).json({error:'License not found'});res.json(l)});
 app.get('/api/compliance/:operatorId',(req,res)=>res.json(dbStore.getCompliance(req.params.operatorId)));app.put('/api/compliance/:operatorId/requirement',(req,res)=>{try{res.json(dbStore.updateComplianceRequirement(req.params.operatorId,req.body.requirementId,req.body.status,getActor(req),req.body.notes))}catch(e:any){res.status(400).json({error:e.message})}});
 if(process.env.NODE_ENV!=='production'){const vite=await createViteServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares)}else{const distPath=path.join(process.cwd(),'dist');app.use(express.static(distPath));app.get('*',(_req,res)=>res.sendFile(path.join(distPath,'index.html')))}
 app.listen(PORT,'0.0.0.0',()=>console.log(`[PNG TPA Platform] Server running on ${PORT}`));}
startServer().catch(err=>console.error('Failed to start PNG TPA Platform server:',err));
